//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYEN()
        {
            this.PHIEUDATCHOes = new HashSet<PHIEUDATCHO>();
            this.HUONGDANVIENs = new HashSet<HUONGDANVIEN>();
        }
    
        public string MACHUYEN { get; set; }
        public Nullable<System.DateTime> TGBATDAU { get; set; }
        public Nullable<System.DateTime> TGKETTHUC { get; set; }
        public Nullable<int> SLTOITHIEU { get; set; }
        public Nullable<int> SLTHUCTE { get; set; }
        public Nullable<int> GIAVE { get; set; }
        public string MALOAI { get; set; }
        public string MATUYEN { get; set; }
        public Nullable<bool> THANHCONG { get; set; }
    
        public virtual LOAICHUYEN LOAICHUYEN { get; set; }
        public virtual TUYEN TUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATCHO> PHIEUDATCHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HUONGDANVIEN> HUONGDANVIENs { get; set; }
    }
}
