//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANHKHACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANHKHACH()
        {
            this.VEs = new HashSet<VE>();
        }
    
        public string MAHK { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string CCCD { get; set; }
        public string PASSPORT { get; set; }
        public Nullable<System.DateTime> NGAYHETHANPASSPORT { get; set; }
        public Nullable<System.DateTime> NGAYHETHANVISA { get; set; }
        public string MAPHIEU { get; set; }
    
        public virtual PHIEUDATCHO PHIEUDATCHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VEs { get; set; }
    }
}
