//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    using TourismManagementSystem.ViewModel;

    public partial class KHACHSAN: BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHSAN()
        {
            this.LICHTRINHs = new HashSet<LICHTRINH>();
        }

        private string _MAKS;
        public string MAKS { get => _MAKS; set { _MAKS = value; OnPropertyChanged(); } }

        private string _TENKS;
        public string TENKS { get => _TENKS; set { _TENKS = value; OnPropertyChanged(); } }

        private string _DIACHI;
        public string DIACHI { get => _DIACHI; set { _DIACHI = value; OnPropertyChanged(); } }

        private string _SDT;
        public string SDT { get => _SDT; set { _SDT = value; OnPropertyChanged(); } }

        private Nullable<int> _SOSAO;
        public Nullable<int> SOSAO { get => _SOSAO; set { _SOSAO = value; OnPropertyChanged(); } }

        private Nullable<int> _SUCCHUA;
        public Nullable<int> SUCCHUA { get => _SUCCHUA; set { _SUCCHUA = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHTRINH> LICHTRINHs { get; set; }
    }
}
