//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTRINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHTRINH()
        {
            this.DICHVUKHACs = new HashSet<DICHVUKHAC>();
            this.KHACHSANs = new HashSet<KHACHSAN>();
            this.NHAHANGs = new HashSet<NHAHANG>();
            this.PHUONGTIENs = new HashSet<PHUONGTIEN>();
        }
    
        public string MALT { get; set; }
        public string MATUYEN { get; set; }
        public string DDBATDAU { get; set; }
        public string DDKETTHUC { get; set; }
        public Nullable<int> NGAYTHU { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        public virtual DIADIEM DIADIEM1 { get; set; }
        public virtual TUYEN TUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DICHVUKHAC> DICHVUKHACs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHSAN> KHACHSANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAHANG> NHAHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHUONGTIEN> PHUONGTIENs { get; set; }
    }
}
