//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    using TourismManagementSystem.ViewModel;

    public partial class PHIEUDATCHO : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDATCHO()
        {
            this.HANHKHACHes = new HashSet<HANHKHACH>();
            this.THONGTINTHANHTOANs = new HashSet<THONGTINTHANHTOAN>();
            this.VEs = new HashSet<VE>();
        }
    
        public string MAPHIEU { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        private string _TINHTRANG;
        public Nullable<int> SLKHACH { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
        public Nullable<int> SOTIENDATHANHTOAN { get; set; }
        public string MACHUYEN { get; set; }
        public string MAKH { get; set; }
    
        public virtual CHUYEN CHUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HANHKHACH> HANHKHACHes { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINTHANHTOAN> THONGTINTHANHTOANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VEs { get; set; }
        public string TINHTRANG { get => _TINHTRANG; set { _TINHTRANG = value; OnPropertyChanged(); } }
    }
}
