//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    using TourismManagementSystem.ViewModel;

    public partial class PHUONGTIEN : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHUONGTIEN()
        {
            this.LICHTRINHs = new HashSet<LICHTRINH>();
        }

        private string _MAPT;
        public string MAPT { get => _MAPT; set { _MAPT = value; OnPropertyChanged(); } }

        private string _TENPT;
        public string TENPT { get => _TENPT; set { _TENPT = value; OnPropertyChanged(); } }
        private Nullable<int> _SLGHE;
        public Nullable<int> SLGHE { get => _SLGHE; set { _SLGHE = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHTRINH> LICHTRINHs { get; set; }
    }
}
