//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGBAO
    {
        public string MATB { get; set; }
        public string THONGBAO1 { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public Nullable<bool> DADOC { get; set; }
    }
}
