//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYEN()
        {
            this.CHUYENs = new HashSet<CHUYEN>();
            this.LICHTRINHs = new HashSet<LICHTRINH>();
        }
    
        public string MATUYEN { get; set; }
        public string TENTUYEN { get; set; }
        public string DDXUATPHAT { get; set; }
        public Nullable<int> GIADUKIEN { get; set; }
        public Nullable<int> SONGAY { get; set; }
        public Nullable<int> SODEM { get; set; }
        public string MALOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYEN> CHUYENs { get; set; }
        public virtual DIADIEM DIADIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHTRINH> LICHTRINHs { get; set; }
        public virtual LOAITUYEN LOAITUYEN { get; set; }
    }
}
