//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        public string MAVE { get; set; }
        public string MAHK { get; set; }
        public string MAPHIEU { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYBAN { get; set; }
        public Nullable<int> GIAVE { get; set; }
    
        public virtual HANHKHACH HANHKHACH { get; set; }
        public virtual PHIEUDATCHO PHIEUDATCHO { get; set; }
    }
}
