name: Continuous Integration

on:
  push:
    branches:
      - branch_Test

jobs:
  build-and-test:

    runs-on: windows-latest       

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up .Net Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: "6.0.x"
      
      - name: Restore dependencies
        run: nuget restore

      - name: Build app
        run: dotnet build

      # - name: Build app
        # run: msBuild /t:"Clean"
      
      # - name: Run test and mutation testing 
        # run: |
         # dotnet test --configuration Release --logger 

      