name: Continuous Integration

on:
  push:
    branches:
      - branch_Test

jobs:
  build-and-test:

    strategy:
      matrix:
        os: [windows-latest]
        architecture: [x64, x84]
        
    runs-on: ${{ matrix.os }}      

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up .Net Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: "6.0.x"
      
      - name: Restore dependencies
        run: nuget restore

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app for release
        run: msbuild C:\Users\DELL\Source\Repos\tourism-management-system_\TourismManagementSystem.sln -t:rebuild -verbosity:diag -property:Configuration=Release

      # - name: Build app
        # run: msBuild /t:"Clean"
      
      # - name: Run test and mutation testing 
        # run: |
         # dotnet test --configuration Release --logger 

      