name: Continuous Integration

on:
  push:
    branches:
      - branch_Test

jobs:
  build-and-test:

    runs-on: windows-latest       

    steps:

      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up .Net Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: ${{ env.BACKEND_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release
      
      # - name: Run test and mutation testing 
        # run: |
         # dotnet test --configuration Release --logger 

      