name: Continuous Integration

on:
  push:
    branches:
      - branch_Test

jobs:
  build-and-test:

    runs-on: windows-latest
    
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      