name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
        dotnet_version: ["5.0", "3.1", "2.1"] 

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core SDK 
        uses: actions/setup-dotnet@v1
        with:
          dotnet_version: ${{ matrix.dotnet_version }} 
          
      - name: Restore NuGet packages
        run: dotnet restore
        
      - name: Install dependencies
        run: dotnet restore # or yarn install

      - name: Build project
        run: dotnet build 
        
      - name: Run tests
        run: dotnet test # or yarn test

      - name: Run mutation testing
        run: dotnet run mutation-test # or yarn mutation-test