name: Continuous Integration

on:
  push:
    branches:
      - branch_Test

env: 
    PROJECT_PATH: TourismManagementSystem/TourismManagementSystem.csproj

jobs:
  build-and-test:

    strategy:
      matrix:
        os: [windows-latest]
        architecture: [x64]
        
    runs-on: ${{ matrix.os }}      

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up .Net Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: "6.0.x" 
      
      - name: Restore dependencies
        run:  dotnet restore ${{ env.PROJECT_PATH }}
        
      - name: Build app 
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore