name: Continuous Integration

on:
  push:
    branches:
      - branch_Test

jobs:
  build-and-test:

    runs-on: windows-latest       

    steps:

      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up .Net Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: "5.0.x"
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Setup MSBuild
        env:
          PATH_FILE: ./.env
        run: |
          echo "##[command]Importing environment from $PATH_FILE"
          cat $PATH_FILE | while read entry || [ -n "$entry" ];
          do
            echo "Adding path entry '$entry' to PATH..."
            echo "::add-path::$entry"
          done

      - name: Build with MSBuild
        run: msbuild /t:Rebuild
      
      # - name: Run test and mutation testing 
        # run: |
         # dotnet test --configuration Release --logger 

      